config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sites, :orders, only: [:index, :show, :new, :create, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/deadline.rb
class Deadline < ActiveRecord::Base
	has_many :orders
	has_many :task, through: :orders
	has_many :users, through: :orders
end

app/models/frequency1.rb
class Frequency1 < ActiveRecord::Base
	has_many :orders
end

app/models/frequency2.rb
class Frequency2 < ActiveRecord::Base
	has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user, optional: true
	belongs_to :task, optional: true
	# belongs_to :deadline
	belongs_to :site, optional: true
	# belongs_to :site2
	# belongs_to :site3
	# belongs_to :site4
	# belongs_to :site5
	# belongs_to :worksheets
	# belongs_to :user1
	# belongs_to :user2
	# belongs_to :frequency1
	# belongs_to :frequency2
  # belongs_to :artist
  # belongs_to :genre
  has_many :comments
  def user_name
    self.user.users if self.user !=nil
  end

  def user_name=(name)
    self.user = User.find_or_create_by(name: name)
  end

  def comments_contents
    self.comments.map do |comment| #map to return a new collection of notes content
      comment.content
    end
  end

  def comment_contents=(comments)#notes argument value is from
    #new.html.erb's Song notes_content
    #binding.pry
   comments.each do |comments|
      self.comments.build(comments: comments) if comments != ""
      #build provides associations and push into collection
   end#binding.pry
   end
  
end

app/models/responsible_party1.rb
class ResponsibleParty1 < ApplicationRecord
end

app/models/responsible_party2.rb
class ResponsibleParty2 < ApplicationRecord
end

app/models/site.rb
class Site < ActiveRecord::Base
	has_many :orders
	has_many :tasks, through: :orders
	has_many :users, through: :orders
    has_many :deadlines, through: :orders
end

app/models/site2.rb
class Site2 < ApplicationRecord
	has_many :orders
	has_many :tasks, through: :orders
	has_many :users, through: :orders
    has_many :deadlines, through: :orders
end

app/models/site3.rb
class Site3 < ApplicationRecord
	has_many :orders
	has_many :tasks, through: :orders
	has_many :users, through: :orders
    has_many :deadlines, through: :orders
end

app/models/site4.rb
class Site4 < ApplicationRecord
	has_many :orders
	has_many :tasks, through: :orders
	has_many :users, through: :orders
    has_many :deadlines, through: :orders
end

app/models/site5.rb
class Site5 < ActiveRecord::Base
	has_many :orders
	has_many :tasks, through: :orders
	has_many :users, through: :orders
    has_many :deadlines, through: :orders
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :orders 
	has_many :users, through: :orders
	has_many :deadlines, through: :orders
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
	has_many :tasks, through: :orders
	has_many :deadlines, through: :orders
end

app/models/user1.rb
class User1 < ActiveRecord::Base
	has_many :orders
	has_many :tasks, through: :orders
    has_many :deadlines, through: :orders
end

app/models/user2.rb
class User2 < ActiveRecord::Base
	has_many :orders
	has_many :tasks, through: :orders
    has_many :deadlines, through: :orders
end

app/models/workorder.rb
class Workorder < ApplicationRecord
end

app/models/worksheet.rb
class Worksheet < ApplicationRecord
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
  	@order = Order.new
	end

	def index 
	@orders = Order.all 
	end 

	def show
	@orders = Order.find(params[:id])
	end 

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    @order.update(order_params)

    if @order.save
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    @order = order.find(params[:id])
    @order.destroy
    flash[:notice] = "order deleted."
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:comment, :tasks, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/workorders_helper.rb
module WorkordersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<ul>
  <% @orders.each do |p| %>
    <li><%= link_to p.id, order_path(p) %></li>
  <% end %>
</ul>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for @order do |f| %>
<p><%= f.collection_select :task_id, Task.all, :id, :tasks %></p>
<!-- collection_select takes 4 arguments -->
<p><%= f.collection_select :site_id, Site.all, :id, :name %></p>
<p><%= f.collection_select :user_id, User.all, :id, :users %></p>
<%= f.submit %>
<% end %>
<br />
<h3>Order comments go here</h3>
<p><input name='order[comment_contents][]' id='order_comments_1'></p>
<!-- #html name, id r always in strings -->
<p><input name='order[comment_contents][]' id='order_comments_2'></p>
<p><input name='order[comment_contents][]' id='order_comments_3'></p>
<!--% end %-->
<%= render 'form' %>
<%= link_to 'Back', orders_path %>